import type { GameItem } from "./types";

export interface CropData extends GameItem {
  category: "crop";

  growTimeSeconds: number;
  seedPrice: number;
  bumpkinLevel: number;

  seedName?: string;
  energyCost?: number;
  xp?: number;
  harvestAmount?: number;
}

export const crops: CropData[] = [
  {
    id: "sunflower",
    name: "Sunflower",
    coinValue: 0.02,
    category: "crop",
    growTimeSeconds: 60,
    seedPrice: 0.01,
    bumpkinLevel: 1,
    verified: true,
    source: "official",
  },
  {
    id: "potato",
    name: "Potato",
    coinValue: 0.14,
    category: "crop",
    growTimeSeconds: 5 * 60,
    seedPrice: 0.1,
    bumpkinLevel: 1,
    verified: true,
    source: "official",
  },
  {
    id: "rhubarb",
    name: "Rhubarb",
    coinValue: 0.24,
    category: "crop",
    growTimeSeconds: 10 * 60,
    seedPrice: 0.15,
    bumpkinLevel: 1,
    verified: true,
    source: "official",
  },
  {
    id: "pumpkin",
    name: "Pumpkin",
    coinValue: 0.4,
    category: "crop",
    growTimeSeconds: 30 * 60,
    seedPrice: 0.2,
    bumpkinLevel: 2,
    verified: true,
    source: "official",
  },
  {
    id: "zucchini",
    name: "Zucchini",
    coinValue: 0.4,
    category: "crop",
    growTimeSeconds: 30 * 60,
    seedPrice: 0.2,
    bumpkinLevel: 2,
    verified: true,
    source: "official",
  },
  {
    id: "carrot",
    name: "Carrot",
    coinValue: 0.8,
    category: "crop",
    growTimeSeconds: 60 * 60,
    seedPrice: 0.5,
    bumpkinLevel: 2,
    verified: true,
    source: "official",
  },
  {
    id: "yam",
    name: "Yam",
    coinValue: 0.8,
    category: "crop",
    growTimeSeconds: 60 * 60,
    seedPrice: 0.5,
    bumpkinLevel: 2,
    verified: true,
    source: "official",
  },
  {
    id: "cabbage",
    name: "Cabbage",
    coinValue: 1.5,
    category: "crop",
    growTimeSeconds: 2 * 60 * 60,
    seedPrice: 1,
    bumpkinLevel: 3,
    verified: true,
    source: "official",
  },
  {
    id: "broccoli",
    name: "Broccoli",
    coinValue: 1.5,
    category: "crop",
    growTimeSeconds: 2 * 60 * 60,
    seedPrice: 1,
    bumpkinLevel: 3,
    verified: true,
    source: "official",
  },
  {
    id: "soybean",
    name: "Soybean",
    coinValue: 2.3,
    category: "crop",
    growTimeSeconds: 3 * 60 * 60,
    seedPrice: 1.5,
    bumpkinLevel: 3,
    verified: true,
    source: "official",
  },
  {
    id: "beetroot",
    name: "Beetroot",
    coinValue: 2.8,
    category: "crop",
    growTimeSeconds: 4 * 60 * 60,
    seedPrice: 2,
    bumpkinLevel: 3,
    verified: true,
    source: "official",
  },
  {
    id: "pepper",
    name: "Pepper",
    coinValue: 3,
    category: "crop",
    growTimeSeconds: 4 * 60 * 60,
    seedPrice: 2,
    bumpkinLevel: 3,
    verified: true,
    source: "official",
  },
  {
    id: "cauliflower",
    name: "Cauliflower",
    coinValue: 4.25,
    category: "crop",
    growTimeSeconds: 8 * 60 * 60,
    seedPrice: 3,
    bumpkinLevel: 4,
    verified: true,
    source: "official",
  },
  {
    id: "parsnip",
    name: "Parsnip",
    coinValue: 6.5,
    category: "crop",
    growTimeSeconds: 12 * 60 * 60,
    seedPrice: 5,
    bumpkinLevel: 4,
    verified: true,
    source: "official",
  },
  {
    id: "eggplant",
    name: "Eggplant",
    coinValue: 8,
    category: "crop",
    growTimeSeconds: 16 * 60 * 60,
    seedPrice: 6,
    bumpkinLevel: 5,
    verified: true,
    source: "official",
  },
  {
    id: "corn",
    name: "Corn",
    coinValue: 9,
    category: "crop",
    growTimeSeconds: 20 * 60 * 60,
    seedPrice: 7,
    bumpkinLevel: 5,
    verified: true,
    source: "official",
  },
  {
    id: "onion",
    name: "Onion",
    coinValue: 10,
    category: "crop",
    growTimeSeconds: 20 * 60 * 60,
    seedPrice: 7,
    bumpkinLevel: 5,
    verified: true,
    source: "official",
  },
  {
    id: "radish",
    name: "Radish",
    coinValue: 9.5,
    category: "crop",
    growTimeSeconds: 24 * 60 * 60,
    seedPrice: 7,
    bumpkinLevel: 5,
    verified: true,
    source: "official",
  },
  {
    id: "wheat",
    name: "Wheat",
    coinValue: 7,
    category: "crop",
    growTimeSeconds: 24 * 60 * 60,
    seedPrice: 5,
    bumpkinLevel: 5,
    verified: true,
    source: "official",
  },
  {
    id: "turnip",
    name: "Turnip",
    coinValue: 8,
    category: "crop",
    growTimeSeconds: 24 * 60 * 60,
    seedPrice: 5,
    bumpkinLevel: 6,
    verified: true,
    source: "official",
  },
  {
    id: "kale",
    name: "Kale",
    coinValue: 10,
    category: "crop",
    growTimeSeconds: 36 * 60 * 60,
    seedPrice: 7,
    bumpkinLevel: 7,
    verified: true,
    source: "official",
  },
  {
    id: "artichoke",
    name: "Artichoke",
    coinValue: 12,
    category: "crop",
    growTimeSeconds: 36 * 60 * 60,
    seedPrice: 7,
    bumpkinLevel: 8,
    verified: true,
    source: "official",
  },
  {
    id: "barley",
    name: "Barley",
    coinValue: 12,
    category: "crop",
    growTimeSeconds: 48 * 60 * 60,
    seedPrice: 10,
    bumpkinLevel: 14,
    verified: true,
    source: "official",
  },
];